### ISSUE TITLE
unable to setup

### ISSUE THREAD

**Issue by bo-tato** [rudolfochrist/ql-https#1]
I'm new at common lisp and quicklisp so I'm probably missing something obvious, but I'm unable to get it working.
I follow the install instructions (there's minor typo missing p in `mkdir ~/quicklis`) and the first steps are fine, the variable `ql-http:*scheme-functions*` does not exist but I still get the use-https restart and it does use curl. So I follow the rest of the instructions and it seems to be set up ok but trying to quickload anything doesn't work, ie:
```
(ql:quickload "alexandria")
```
gives error: `System "alexandria" not found`
I tried also: `(ql:update-dist "quicklisp")` and get the error:
```
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION QL-DIST:AVAILABLE-UPDATE (1)>
when called with arguments
  (NIL).
```
I'm on SBCL version 2.2.9.debian

**Comment by bo-tato** [comment]
it is working after also doing:
```
(ql-dist:install-dist "https://beta.quicklisp.org/dist/quicklisp.txt")
```

**Comment by bo-tato** [comment]
also it'd be nice to add to the section 4.3 Startup that you can add that code to `~/.sbclrc` if you're using sbcl, to get the equivalent behaviour of quicklisp `(ql:add-to-init-file)`, also would be nice to remove the | around the startup code in readme so it can be easier copy pasted into init file.
thanks for making more secure patch of quicklisp, i'm just documenting here what stumbling blocks i run into setting it up if you want to make documentation and setup as easy as possible for cl newbies

**Comment by rudolfochrist** [comment]
Thanks for trying it out and improving the documentation. Indeed there were some errors in the installation instructions. Unfortunately I cannot reproduce the error you've experienced. 

Is it possible for you to give the updated instructions in #2  a try and report back if everything works as expected? I've created an asciicast of the installation and hopefully it should work the same on your system. 

see: https://asciinema.org/a/585361

**Comment by rudolfochrist** [comment]
> also it'd be nice to add to the section 4.3 Startup that you can add that code to `~/.sbclrc` if you're using sbcl, to get the equivalent behaviour of quicklisp `(ql:add-to-init-file)`

This would be a PR I would definitely accept. 😉

>also would be nice to remove the | around the startup code in readme so it can be easier copy pasted into init file. 

Done in #2 

> thanks for making more secure patch of quicklisp, i'm just documenting here what stumbling blocks i run into setting it up if you want to make documentation and setup as easy as possible for cl newbies

Thank you. And thank you for doing the same by trying things out and report back what works and what doesn't. 👍

**Comment by bo-tato** [comment]
thanks, it's nicer now with the markdown and ASCIInema. I can't reproduce either the error I had before. I tried in a clean container with the same debian and sbcl version and it worked fine

**Comment by rudolfochrist** [comment]
Great. Thanks for checking.
