### ISSUE TITLE
Work without extra dependencies on Mac OSX

### ISSUE THREAD

**Issue by bo-tato** [rudolfochrist/ql-https#11]
Currently we're using `md5sum` (except on sbcl which has md5sum builtin), and `sha256sum` for the install script, neither of which seem installed by default on Macs. I think we could use openssl:
```
openssl dgst -md5 FILENAME
openssl dgst -sha256 FILENAME
```
or `shasum -a 256 FILENAME`. Either option should work on default installs of most mac and linux I think. I don't have a mac to test on though, if someone with a mac can help test that'd be great, to know if those changes work and are the only changes needed to work without extra dependencies on Macs.

**Comment by rudolfochrist** [comment]
There is also the `md5` program on Macs, but I would prefer the `openssl` variant. I guess the assumption holds that if `curl` is installed then `openssl` is also present. And by using `openssl` we handle those platforms that don't have `md5sum` and `sha256sum` as well as those without `md5` and `shasum`.
