### ISSUE TITLE
md5-mismatch for every download

### ISSUE THREAD

**Issue by swapneils** [rudolfochrist/ql-https#8]
Every time I try to load a system with this package, I'm running into an `md5-mismatch` error. When using the "retry evaluation" or "register local projects" restarts, the code runs fine. 

Is there a mismatch between how quicklisp calculates md5 hashes and how we're calculating them in our own function?

**Comment by rudolfochrist** [comment]
Hmm, 
we're using `md5sum` underneath. Can you run `md5sum --version` and paste it's output here. Can you paste a full backtrace as well? Currently I cannot reproduce this. Thank you.

**Comment by bo-tato** [comment]
What is your result of `(ql-dist:enabled-dists)`? I realized the md5 checking function is using `ql-dist:find-release` which is looping over enabled-dists and returning the first match. Maybe it is possible that quicklisp tries to install from one dist, but the md5 it gets from another. Like rudolfochrist says full backtrace of error and what quicklisp commands you're running would help a lot to reproduce and debug this.

**Comment by swapneils** [comment]
Installing md5sum in the command line resolved this issue, apparently mac systems don't have it by default. Aside from a README update I think we can close this ticket as non-actionable.

**Comment by bo-tato** [comment]
In https://github.com/rudolfochrist/ql-https/pull/10 I changed it to use sb-md5 to compute md5sum if we are on sbcl. And if not on sbcl it will still shell out to md5sum, but should signal a clear error that `Couldn't execute "md5sum": No such file or directory` rather than just getting md5-mismatch later.

**Comment by rudolfochrist** [comment]
> Installing md5sum in the command line resolved this issue, apparently mac systems don't have it by default. 

Interesting. Perhaps we should adjust the `install.sh` script as well, because it uses `sha256sum` and I guess this also isn't on macos by default.

**Comment by bo-tato** [comment]
From what I can tell internet searching it seems on mac osx it should work both openssl: `openssl dgst -sha256 FILENAME` or `shasum -a 256 FILENAME`, both of which work also a basic install of debian and arch linux at least.
