### ISSUE TITLE
Does this actually work? I’m hopeful that it does 

### ISSUE THREAD

**Issue by ghost** [rudolfochrist/ql-https#9]
Hello, I’m wondering if this allows me to use Quicklisp to download over https why hasn’t the quicklisp developer implement something similar?

anyways I’m going to start using this. Thanks

**Comment by bo-tato** [comment]
see the discussion at https://github.com/quicklisp/quicklisp-client/issues/167
basically this isn't completely portable as only 99% of systems have curl, not 100%. also certificate authorities can forge https certificates, it's better to verify signatures from the package developers and they're developing some signature verification scheme but don't really have time to work on it so it just stays how it is

**Comment by daninus14** [comment]
Is it possible to make a check if curl is available in the system? If it is, use curl for https, if it's not, then use the regular http way the way quicklisp does it. At least that way we would have a preferred https over http if it's available.

They may also accept a PR since it will not break anything while theydo the signature verification.

What do you think?

**Comment by daninus14** [comment]
Ok, it's not so complicated

```common-lisp
(uiop:run-program "curlaiwdnjawn -V")
```

Will give an error, we just have to wrap it in a `handler-case`.

```common-lisp
(uiop:run-program "curl -V")
```

This last version works, and it's the same for windows it looks like. So before any request, we can just check...

It's really not complicated

**Comment by daninus14** [comment]
On windows it could be it's `curl --version` https://farmwrangler.com/blog/how-to-check-if-curl-is-installed/

not running on windows so I don't know...

**Comment by rudolfochrist** [comment]
@daninus14 
Sure. PRs are welcome.

**Comment by daninus14** [comment]
Ok, can you at least guide me as to where I have to make the change since it's your code base?

**Comment by rudolfochrist** [comment]
@daninus14 let's  take this discussion to its own issue. -> #17
